trigger:
  branches:
    include:
      - main
      - master
      - hotfix*

pr:
  branches:
    include:
      - main
      - master
      - hotfix*

pool:
  name: "ch-mg-ue2-agent-pool-mdp001"
  demands:
    - agent.os -equals Linux
    - ImageOverride -equals ubuntu-22.04-covera-build

variables:
  - group: covera-build
  - name: CODE_COVERAGE_TARGET_PERCENTAGE
    value: "80"
  - name: JFROG_CRITICAL_VULNERABILITY_THRESHOLD_COUNT
    value: "0"
  - name: PROJECT_NAME
    value: "qcc-gateway-hl7-listener"
  - name: IMAGE_DEFAULT_TAG
    value: "1.0.0"

parameters:
  - name: pythonVersion
    type: string
    default: "3.11.7"
  - name: appDeploymentsBranch
    type: string
    default: "refs/heads/main"

resources:
  repositories:
    - repository: azureDevOpsTemplates
      type: github
      name: coverahealth/app-deployments
      ref: "${{ parameters.appDeploymentsBranch }}"
      endpoint: coverahealth

stages:
  - stage: BuildAndTest
    displayName: "Build and Test"
    jobs:
      - job: Install_Test_Build
        displayName: "Build and Test"
        steps:
          - checkout: self
            fetchDepth: 0

          - template: azure-devops-templates/poetry-config-template.yaml@azureDevOpsTemplates
            parameters:
              pythonVersion: "${{ parameters.pythonVersion }}"

          - template: azure-devops-templates/poetry-install-template.yaml@azureDevOpsTemplates

          - template: azure-devops-templates/poetry-test-template.yaml@azureDevOpsTemplates
            parameters:
              codeCoverageThreshold: "$(CODE_COVERAGE_TARGET_PERCENTAGE)"

          - template: azure-devops-templates/sonarcloud-scan-template.yaml@azureDevOpsTemplates

          - template: azure-devops-templates/poetry-build-template.yaml@azureDevOpsTemplates

          - script: |
              export BUILD_TS_TAG="$(IMAGE_DEFAULT_TAG)-$(date -u +%Y%m%d%H%M%S)"
              echo "##vso[task.setvariable variable=BUILD_TS_TAG;isOutput=true]$BUILD_TS_TAG"
            name: SetBuildTsTag
            displayName: "Set Build Timestamp"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "dist"
              artifact: "python_package"
            displayName: "Save Built Package as Pipeline Artifact"

  - stage: DockerBuild
    dependsOn: BuildAndTest
    variables:
      buildTsTag: $[stageDependencies.BuildAndTest.Install_Test_Build.outputs['SetBuildTsTag.BUILD_TS_TAG']]
    jobs:
      - job: Build_And_Scan_Images
        steps:
          - checkout: self
            clean: true
            fetchDepth: 1
            persistCredentials: true

          - template: azure-devops-templates/poetry-config-template.yaml@azureDevOpsTemplates
            parameters:
              pythonVersion: "${{ parameters.pythonVersion }}"

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: "python_package"
              path: "$(Build.SourcesDirectory)/dist"
            displayName: "Download Built Package"

          - template: azure-devops-templates/docker-login-template.yaml@azureDevOpsTemplates
            parameters:
              containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION)

          - template: azure-devops-templates/docker-login-template.yaml@azureDevOpsTemplates
            parameters:
              containerRegistry: $(JFROG_REGISTRY_SERVICE_CONNECTION)

          - template: azure-devops-templates/docker-build-template.yaml@azureDevOpsTemplates
            parameters:
              containerRegistry: $(JFROG_REGISTRY_SERVICE_CONNECTION)
              repository: "$(ARTIFACTS_JFROG_DOCKER_REPOSITORY)/$(PROJECT_NAME)"
              dockerfile: "Dockerfile"
              buildContext: "."
              imageTag: "$(IMAGE_DEFAULT_TAG)"
              buildTsTag: "$(buildTsTag)"

          - template: azure-devops-templates/docker-publish-artifact-template.yaml@azureDevOpsTemplates
            parameters:
              projectName: "$(PROJECT_NAME)"
              dockerRegistry: "$(ARTIFACTS_JFROG_DOCKER_REGISTRY)"
              dockerRepository: "$(ARTIFACTS_JFROG_DOCKER_REPOSITORY)"
              imageTag: "$(IMAGE_DEFAULT_TAG)"

          - template: azure-devops-templates/docker-image-scan-template.yaml@azureDevOpsTemplates
            parameters:
              dockerRegistry: "$(ARTIFACTS_JFROG_DOCKER_REGISTRY)"
              dockerRepository: "$(ARTIFACTS_JFROG_DOCKER_REPOSITORY)"
              imageName: "$(PROJECT_NAME)"
              imageTag: "$(IMAGE_DEFAULT_TAG)"
              vulnerabilityThresholdCount: "$(JFROG_CRITICAL_VULNERABILITY_THRESHOLD_COUNT)"

  - stage: PushToRepository
    displayName: Push Docker image to ACR
    dependsOn: [BuildAndTest, DockerBuild]
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')))
    variables:
      buildTsTag: $[stageDependencies.BuildAndTest.Install_Test_Build.outputs['SetBuildTsTag.BUILD_TS_TAG']]
    jobs:
      - template: azure-devops-templates/docker-multiple-push-template.yaml@azureDevOpsTemplates
        parameters:
          projectName: "$(PROJECT_NAME)"
          containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION)
          repository: "development-docker"
          acrRegistryUrl: "$(ACR_URL)"
          imageTag: "$(IMAGE_DEFAULT_TAG)"
          buildTsTag: "$(buildTsTag)"
          prefix: "$(PREFIX)"
